
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
[Config]
public partial class AIConfigCategory
{
    public static AIConfigCategory Instance;

    private Dictionary<int, AIConfig> dict;
    private List<AIConfig> list;
    
    public AIConfigCategory(ByteBuf _buf)
    {
        Instance = this;
        dict = new Dictionary<int, AIConfig>();
        list = new List<AIConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            AIConfig _v;
            _v = AIConfig.DeserializeAIConfig(_buf);
            list.Add(_v);
            dict.Add(_v.Id, _v);
        }
        this.AfterEndInit();
    }

    public Dictionary<int, AIConfig> Dict => dict;
    public List<AIConfig> List => list;

    public AIConfig GetOrDefault(int key) => dict.TryGetValue(key, out var v) ? v : null;
    public AIConfig Get(int key) => dict[key];
    public AIConfig this[int key] => dict[key];

    public void ResolveRef()
    {
        foreach(var _v in list)
        {
            _v.ResolveRef();
        }
    }

    partial void AfterEndInit();

}

}

