
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
[Config]
public partial class StartProcessConfigCategory
{
    public static StartProcessConfigCategory Instance;

    private Dictionary<int, StartProcessConfig> dict;
    private List<StartProcessConfig> list;
    
    public StartProcessConfigCategory(ByteBuf _buf)
    {
        Instance = this;
        dict = new Dictionary<int, StartProcessConfig>();
        list = new List<StartProcessConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            StartProcessConfig _v;
            _v = StartProcessConfig.DeserializeStartProcessConfig(_buf);
            list.Add(_v);
            dict.Add(_v.Id, _v);
        }
        this.AfterEndInit();
    }

    public Dictionary<int, StartProcessConfig> Dict => dict;
    public List<StartProcessConfig> List => list;

    public StartProcessConfig GetOrDefault(int key) => dict.TryGetValue(key, out var v) ? v : null;
    public StartProcessConfig Get(int key) => dict[key];
    public StartProcessConfig this[int key] => dict[key];

    public void ResolveRef()
    {
        foreach(var _v in list)
        {
            _v.ResolveRef();
        }
    }

    partial void AfterEndInit();

}

}

