
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
[Config]
public partial class StartMachineConfigCategory
{
    public static StartMachineConfigCategory Instance;

    private Dictionary<int, StartMachineConfig> dict;
    private List<StartMachineConfig> list;
    
    public StartMachineConfigCategory(ByteBuf _buf)
    {
        Instance = this;
        dict = new Dictionary<int, StartMachineConfig>();
        list = new List<StartMachineConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            StartMachineConfig _v;
            _v = StartMachineConfig.DeserializeStartMachineConfig(_buf);
            list.Add(_v);
            dict.Add(_v.Id, _v);
        }
        this.AfterEndInit();
    }

    public Dictionary<int, StartMachineConfig> Dict => dict;
    public List<StartMachineConfig> List => list;

    public StartMachineConfig GetOrDefault(int key) => dict.TryGetValue(key, out var v) ? v : null;
    public StartMachineConfig Get(int key) => dict[key];
    public StartMachineConfig this[int key] => dict[key];

    public void ResolveRef()
    {
        foreach(var _v in list)
        {
            _v.ResolveRef();
        }
    }

    partial void AfterEndInit();

}

}

