
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
[Config]
public partial class StartZoneConfigCategory
{
    public static StartZoneConfigCategory Instance;

    private Dictionary<int, StartZoneConfig> dict;
    private List<StartZoneConfig> list;
    
    public StartZoneConfigCategory(ByteBuf _buf)
    {
        Instance = this;
        dict = new Dictionary<int, StartZoneConfig>();
        list = new List<StartZoneConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            StartZoneConfig _v;
            _v = StartZoneConfig.DeserializeStartZoneConfig(_buf);
            list.Add(_v);
            dict.Add(_v.Id, _v);
        }
        this.AfterEndInit();
    }

    public Dictionary<int, StartZoneConfig> Dict => dict;
    public List<StartZoneConfig> List => list;

    public StartZoneConfig GetOrDefault(int key) => dict.TryGetValue(key, out var v) ? v : null;
    public StartZoneConfig Get(int key) => dict[key];
    public StartZoneConfig this[int key] => dict[key];

    public void ResolveRef()
    {
        foreach(var _v in list)
        {
            _v.ResolveRef();
        }
    }

    partial void AfterEndInit();

}

}

