
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class StartProcessConfig : Luban.BeanBase
{
    public StartProcessConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MachineId = _buf.ReadInt();
        InnerPort = _buf.ReadInt();
        AppName = _buf.ReadString();
        this.AfterEndInit();
    }

    public static StartProcessConfig DeserializeStartProcessConfig(ByteBuf _buf)
    {
        return new StartProcessConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属机器
    /// </summary>
    public readonly int MachineId;
    /// <summary>
    /// 内网端口
    /// </summary>
    public readonly int InnerPort;
    /// <summary>
    /// 程序名
    /// </summary>
    public readonly string AppName;
   
    public const int __ID__ = 2140444015;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "MachineId:" + MachineId + ","
        + "InnerPort:" + InnerPort + ","
        + "AppName:" + AppName + ","
        + "}";
    }
}

}
