
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
[Config]
public partial class StartSceneConfigCategory
{
    public static StartSceneConfigCategory Instance;

    private Dictionary<int, StartSceneConfig> dict;
    private List<StartSceneConfig> list;
    
    public StartSceneConfigCategory(ByteBuf _buf)
    {
        Instance = this;
        dict = new Dictionary<int, StartSceneConfig>();
        list = new List<StartSceneConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            StartSceneConfig _v;
            _v = StartSceneConfig.DeserializeStartSceneConfig(_buf);
            list.Add(_v);
            dict.Add(_v.Id, _v);
        }
        this.AfterEndInit();
    }

    public Dictionary<int, StartSceneConfig> Dict => dict;
    public List<StartSceneConfig> List => list;

    public StartSceneConfig GetOrDefault(int key) => dict.TryGetValue(key, out var v) ? v : null;
    public StartSceneConfig Get(int key) => dict[key];
    public StartSceneConfig this[int key] => dict[key];

    public void ResolveRef()
    {
        foreach(var _v in list)
        {
            _v.ResolveRef();
        }
    }

    partial void AfterEndInit();

}

}

